#FROM - base image we want to use
#WORKDIR - setting up the working directory of /app
#COPY - copying the package.json file over
#RUN - run the npm installation
#COPY - copy the rest of this local directory over
#CMD - run commands npm, run, start

FROM node:16-alpine

WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "start"]